name: Build and Pack 'dev'

on:
    push:
        branches:
            - 'feature/GitHubActions'
        paths-ignore:
            - '**/*.md'
            - 'mkdocs.yml'
            - 'src/docs/**/*'

jobs:
    ci-pipeline:
        name: 'Continuous Integration pipeline'
        runs-on: 'windows-latest'
        env:
            BUILD_VERSION: 1.0.0
            BUILD_VERSION_SUFFIX: gha-10000
            DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            ORGANIZATION_NAME: ${{ github.event.repository.owner.name }}
        steps:
            - uses: actions/checkout@master
            - name: Initialize
              run: |
                echo .NET Core & dotnet --version & echo.
                echo NodeJS & node --version & echo.
                echo NPM & npm version & echo.
                git config --global core.autocrlf true
            - name: Restore NuGet packages
              run: dotnet restore "src\OrchardCore\OrchardCore\OrchardCore.csproj" /nodeReuse:false
            - name: Build solution
              shell: powershell
              run: dotnet build "src\OrchardCore\OrchardCore\OrchardCore.csproj" --configuration Release --version-suffix $env:BUILD_VERSION_SUFFIX --no-restore /nodeReuse:false
#            - name: Run tests
#              run: |
#                dotnet test .\test\OrchardCore.Tests\OrchardCore.Tests.csproj --configuration Release --no-build
#                cd .\test\Functional
#                test-setup.cmd
#                test-run.cmd
            - name: Package solution
              shell: powershell
              run: dotnet pack "src\OrchardCore\OrchardCore\OrchardCore.csproj" --version-suffix $env:BUILD_VERSION_SUFFIX --configuration Release --output build --no-build /nodeReuse:false
            - name: Add GitHub Package Registry as NuGet package source
              shell: powershell
              run: dotnet nuget sources add -name "GPR" -Source "https://nuget.pkg.github.com/$($env:ORGANIZATION_NAME)/index.json" -Username $($env:ORGANIZATION_NAME) -Password ${{ secrets.GITHUB_TOKEN }}
            - name: Publish packages
              shell: powershell
              run: dotnet nuget push "build\OrchardCore.$($env:BUILD_VERSION)-$($env:BUILD_VERSION_SUFFIX).nupkg" --source "GPR"